name: default
on:
  push:
    branches:
    - '*'
jobs:
    build-node: 
      runs-on: ubuntu-latest
      steps:
          - run: node --version
          - run: npm --version
          - run: actions/checkout@v1
          - run:  npm install
          - run: node server.js